config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resource :session, only: [:new, :create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  

end

app/models/user.rb
class User < ApplicationRecord
    validates :password, length: { minimum: 6, allow_nil: true}
    validates :password_digest, presence: true
    validates :email, :session_token, presence: true, uniqueness: true
    after_initialize :ensure_session_token
    attr_reader :password

    # def self.generate_session_token
    # end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            return user
        end
        nil 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    session[:session_token] = nil
    if current_user
      current_user.reset_session_token!
    end
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!(current_user)
  end

  def require_logged_out
    redirect_to users_url if logged_in?
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_logged_out, only:[:new, :creates]
    def new
    end

    def create
        @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if @user
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = ["INVALID CREDENTIALS"]
            render :new
        end

    end

    def destroy
        logout!
        redirect_to new_session_url
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    def edit
        @user = User.find(params[:id])
        render :edit
    end

    def index
        @users = User.all        
        render :index
    end

    def show
        @user = User.find_by(id: params[:id])
        if @user
            render :show
        else
            render json: "No user found.", status: 404
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login! (@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_url(@user)
        else
            render json: @user.errors.full_messages, status: 422
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_url
    end

    private

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>YAHAHA</h1>
      <% if logged_in? %>
      <h2>Welcome <%= current_user.email %></h2>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Log Out :(">
      </form>
    <% else %>
      <a href="<%= new_session_url %>">Sign In</a>
      <a href="<%= new_user_url %>">Sign Up</a>
    <% end %>

    <% if flash[:errors] %>
      <ul>
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%
    if type == :new
        header_text = "Create New User"
        action = users_url
        button_text = "Create you!"
    else
        header_text = "Edit This User"
        action = user_url(user)
        button_text = "Changem!"
    end
%>

<h1><%= header_text %></h1>

<form action="<%= action %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <%# overwrite the method %>
    <% if type == :edit %>
        <input type="hidden" name="_method" value="patch">
    <% end %>

    <br>
    <label >Email:
        <input type="email" name="user[email]" value="<%= user.email %>">
    </label>
    <br>

    <label for="user_password">Password</label>
    <input id="user_password" type="password" name="user[password]" value="<%= user.password %>">
    <br>

    <input type="submit" value="<%= button_text %>">
</form>

app/views/users/_user.html.erb
<ul>
    <li><%= user.email %></li>
    
    <% if action == :show %>
        <li><a href="<%= users_url %>">User Index</a></li>
    <% else %>
    <li><a href="<%= user_url(user) %>">User Show</a></li>
    <% end %>
</ul>

app/views/users/edit.html.erb
<%= render 'form', user: @user, type: :edit %>

app/views/users/index.html.erb
<h1>These are our users</h1>

<a href="<%= new_user_url %>">Create new User</a>
<ul>
    <% @users.each do |single_user| %>
        <li> 
            <%= render 'user', user: single_user, action: :index %>
        </li>
        <br>
    <% end %>
</ul>

app/views/users/new.html.erb
<%= render 'form', user: @user, type: :new %>

app/views/users/show.html.erb
<%= render 'user', user: @user, action: :show %>
<a href="<%= edit_user_url(@user) %>">Edit me.</a>
<form action="<%= user_url(@user) %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Avadakadavra!!!!">
</form>